pipeline:
  build:
    image: node
    commands:
      - npm install
    when:
      branch: [ development, greenkeeper/*, staging ]

  # Smoke tests
  lint:
    image: node
    commands:
      - npm run lint
    when:
      branch: [ development, greenkeeper/* ]

  test - development:
    image: node
    commands:
      - npm test
      - rm -rf assets/bundles # Remove dev bundles
    when:
      branch: [ development, greenkeeper/* ]

  test - production:
    image: node
    commands:
      - npm run build
      - npm test --production
    when:
      branch: [ development, greenkeeper/* ]

  # Add to staging branch
  stage:
    image: node
    commands:
      - git config --global user.email "apps@nexus-stats.com"
      - git config --global user.name "nexus-ci"
      - sed -i '/\\/assets\\/bundles\\//d' .gitignore # Keep webpack builds
      - git stash
      - git fetch origin
      - git checkout development
      - git checkout staging
      - git merge -s recursive -X theirs development
      - git stash apply
      - git add -A
      - git commit -m "Add staging builds"
      - git push 'https://nexus-ci:'$NEXUS_CI_TOKEN'@github.com/nexus-devs/nexus-stats' staging 2>/dev/null
        # ^ suppress output to /dev/null to keep secrets hidden
    secrets: [ nexus_ci_token ]
    when:
      branch: development

  # Deploy on staging server
  deploy:
    image: node
    commands:
      - echo "We're not quite there yet 😉"
    when:
      branch: staging

  # Final release to production
  release:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npm run release
    secrets: [ gh_token ]
    when:
      branch: master

services:
  mongodb:
    image: mongo
  redis:
    image: redis
