pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm run toggle-webpack
    when:
      branch: [ development, greenkeeper/* ]

  # Smoke tests
  lint:
    image: node
    commands:
      - npm run lint
    when:
      branch: [ development, greenkeeper/* ]

  test - development:
    image: node
    commands:
      - npm test
    when:
      branch: [ development, greenkeeper/* ]

  test - production:
    image: node
    commands:
      - npm run build
      - npm test --production
    when:
      branch: [ development, greenkeeper/* ]

  # Add to staging branch
  stage:
    image: node
    commands:
      - git config --global user.email "apps@nexus-stats.com"
      - git config --global user.name "nexus-ci"
      - sed -i '/\\/assets\\/bundles\\//d' .gitignore # Keep webpack builds
      - git fetch origin
      - git add -A
      - git commit -m "Add staging builds"
      - git checkout development
      - git add -A
      - git commit -m "Add staging builds"
      - git checkout staging
      - git merge -s recursive -X theirs development
      - git push 'https://nexus-ci:'$NEXUS_CI_TOKEN'@github.com/nexus-devs/nexus-stats' staging 2>/dev/null
        # ^ suppress output to /dev/null to keep secrets hidden
    secrets: [ nexus_ci_token ]
    when:
      branch: development
      event: [ push ]

  # Deploy on staging server
  docker:
    image: alpine/git
    commands:
      - mkdir -p docker
      - cd docker
      - git init
      - git remote add origin https://github.com/nexus-devs/docker.git
      - git fetch --all
      - git checkout master
    when:
      branch: staging
  deploy:
    image: plugins/docker
    repo: nexusstats/nexus-stats
    dockerfile: docker/app/prod/Dockerfile
    context: docker/app/prod/
    no_cache: true
    secrets: [ docker_username, docker_password ]
    when:
      branch: staging

  # Final release to production
  release:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npm run release
    secrets: [ gh_token ]
    when:
      branch: master
      event: [ push ]

services:
  mongodb:
    image: mongo
    when:
      branch: [ development, greenkeeper/* ]
  redis:
    image: redis
    when:
      branch: [ development, greenkeeper/* ]
